version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER = postgres
      - POSTGRES_PASSWORD = postgres
    ports:
      - "5432:5432"
    volumes:
      - db: ./postgres-data:/var/lib/postgresql/data

    logging:
      options:
        max-size: 10m
      max-file: "3"

  volumes:
    db:
      driver: local